version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.15.8

    steps:
      - checkout
      - run: make build


  test:
    docker:
      - image: cimg/go:1.15.8

    steps:
      - checkout
      - run: go test -v ./...
    

  build-release:
    docker:
      - image: cimg/go:1.15.8

    steps:
      - checkout
      - run: go test -v ./...
      - run: make release
      - run: mkdir -p /tmp/workspace/artifacts
      - run: cp cmd/kubectl-cost/kubectl-cost-darwin-amd64 /tmp/workspace/artifacts
      - run: cp cmd/kubectl-cost/kubectl-cost-linux-amd64 /tmp/workspace/artifacts
      - run: cp cmd/kubectl-cost/kubectl-cost-windows-amd64 /tmp/workspace/artifacts

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - artifacts
  release:
    docker:
      - image: cimg/go:1.15.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace/artifacts

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test

  build-and-release:
    jobs:
      - build-release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build-release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
