name: PR - build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Install govvv
        run: |
          go get github.com/ahmetb/govvv@master

      - name: Make build
        run: |
          make build

